{
  imports = [
    ./neo-tree.nix
    ./treesitter.nix
    ./devicons.nix
    ./telescope.nix
    ./fugitive.nix
    ./lualine.nix
    ./lsp.nix
    ./nvim-tmux.nix
    ./cmp.nix
    ./trouble.nix
    ./autopairs.nix
    ./alpha.nix
    ./indent-blankline.nix
    ./comment.nix
    ./gitsigns.nix
  ];
}
